In [1]:
import pandas as pd
path = "/Users/yusuf.bektas/Quant/drl-crypto/results/20250726_183550_longshort_1800s_c00002/best_model/validation_rewards.csv"
df = pd.read_csv(path, index_col=False)
df

      step  log_return  cum_log_return
0        0   -0.001210       -0.001210
1        1    0.004208        0.002998
2        2    0.001235        0.004233
3        3   -0.003517        0.000717
4        4    0.000207        0.000924
...    ...         ...             ...
4257  4257   -0.002630        0.259960
4258  4258    0.000271        0.260231
4259  4259    0.000107        0.260338
4260  4260    0.000558        0.260896
4261  4261   -0.002052        0.258844

[4262 rows x 3 columns]

In [16]:
import pandas as pd
w_path = "/Users/yusuf.bektas/Quant/drl-crypto/results/20250727_010828_longshort_1800s_c00000/best_model/validation_weights.csv"
w_df = pd.read_csv(w_path, index_col=False)
w_df

,ETHUSDT,ADAUSDT,BNBUSDT,DOGEUSDT,SOLUSDT,XRPUSDT,BTCUSDT,CASH_weight
0,-0.087766,-0.049306,-0.085226,0.432161,-0.087653,-0.158525,-0.086797,1.123112
1,0.044296,-0.355885,0.049790,0.220606,0.029527,-0.177338,0.050273,1.138731
2,-0.111641,-0.090100,-0.108673,0.430226,-0.108520,0.017582,-0.110616,1.081744
3,0.109930,-0.121582,0.112911,-0.338529,0.101078,-0.098700,0.112092,1.122801
4,-0.009339,0.018354,-0.001181,-0.457675,-0.017716,0.195433,-0.002556,1.274680
...,...,...,...,...,...,...,...,...
4257,0.124832,-0.154101,0.124076,-0.270792,0.134154,-0.058713,0.124393,0.976152
4258,-0.122880,-0.010609,-0.123262,0.172566,-0.131746,0.274956,-0.122924,1.063899
4259,0.066655,-0.119551,0.063160,-0.235598,0.064339,-0.239954,0.063962,1.336988
4260,-0.042749,-0.036103,-0.042237,0.508746,-0.044964,-0.278476,-0.041819,0.977602
4261,-0.021456,-0.346155,-0.023113,-0.266863,-0.033214,0.133662,-0.022113,1.579253

In [19]:

w_df.abs().sum(axis=1).describe()

count    4262.000000
mean        1.886897
std         0.261109
min         1.000000
25%         1.752171
50%         1.927658
75%         2.064735
max         2.686062
dtype: float64

Commission rate: 0.0002
Weight change: tensor([ 0.1000, -0.1000,  0.1000, -0.1000])
Turnover: 0.400000
Commission factor (mu): 0.999960
Commission cost: 0.0040%

Validation data shape:
Weights: (4262, 8)
Rewards: (4262, 3)
Price ratios: (4262, 7)

Weight constraint check:
Weight sums (should be ~1.0): min=1.000000, max=1.000000, mean=1.000000

Commission rate from filename: 0.0

First 9 turnovers: [np.float64(1.870194712), np.float64(2.039039561), np.float64(1.2791566369999998), np.float64(1.959643453), np.float64(1.700768124), np.float64(1.32631128), np.float64(1.65854122), np.float64(1.293105212), np.float64(1.2934237149999999)]
Average turnover: 1.602243

Step 1:
  Weights prev: [-0.0234224   0.02665448 -0.01952048 -0.49396986]
  Price ratios: [1.0057483 1.0086114 1.0028263 1.0055425]
  Turnover: 1.870195
  Commission factor (mu): 0.999813
  Portfolio return: 1.000606
  Log reward: 0.000419
  Recorded reward: 0.000606
  Difference: 0.00018706

Step 2:
  Weights prev: [ 0.09490246  0.01474604  0.09736622 -0.06471749]
  Price ratios: [0.9989975  0.99573106 1.0088364  0.99874187]
  Turnover: 2.039040
  Commission factor (mu): 0.999796
  Portfolio return: 1.001435
  Log reward: 0.001230
  Recorded reward: 0.001434
  Difference: 0.00020393

Step 3:
  Weights prev: [-0.11415535  0.2690783  -0.11137609 -0.25355607]
  Price ratios: [0.99354255 0.9958659  0.9994577  0.9938812 ]
  Turnover: 1.279157
  Commission factor (mu): 0.999872
  Portfolio return: 1.001954
  Log reward: 0.001824
  Recorded reward: 0.001952
  Difference: 0.00012791

Step 4:
  Weights prev: [ 0.01104357  0.15867741  0.01942193 -0.5279067 ]
  Price ratios: [1.0026568 0.999385  0.9976159 1.000845 ]
  Turnover: 1.959643
  Commission factor (mu): 0.999804
  Portfolio return: 0.998765
  Log reward: -0.001431
  Recorded reward: -0.001235
  Difference: 0.00019600

Step 5:
  Weights prev: [ 0.08290823 -0.18685922  0.08408151  0.06679139]
  Price ratios: [0.9949303  0.9946154  0.9955335  0.99185866]
  Turnover: 1.700768
  Commission factor (mu): 0.999830
  Portfolio return: 1.001122
  Log reward: 0.000951
  Recorded reward: 0.001121
  Difference: 0.00017005

Reward comparison (first 19 steps):
Manual calculation mean: 0.000076
Recorded rewards mean: 0.000252
Max absolute difference: 0.00025962
Mean absolute difference: 0.00017585